name: Deploy to Cloudflare
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - run: yarn global add wrangler
      - run: echo $GIT_BRANCH
        env:
          GIT_BRANCH: ${{ env.GIT_BRANCH }}
      - run: CF_API_TOKEN=${CLOUDFLARE_API_TOKEN} CF_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID} wrangler pages publish apps/example --project-name full-stack-cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
